version: '3'

services:
  openldap:
    image: osixia/openldap:1.1.9
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION="Nome da Organização"
      - LDAP_DOMAIN=imdb.app.org
      - LDAP_ADMIN_PASSWORD=imdbapp
      - LDAP_READONLY_USER="true"
      - LDAP_READONLY_USER_USERNAME="readonly"
      - LDAP_READONLY_USER_PASSWORD="readonly"
    volumes:
      - ./login/data/ldap/data:/var/lib/ldap
      - ./login/data/ldap/slapd.d:/etc/ldap/slapd.d
  
  mongodb:
    image: mongo:3.6.1
    container_name: uv-mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  jaeger:
    image: jaegertracing/all-in-one
    environments: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
  
